### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by robguinness** [fossology/atarashi#45]
Hi, I'm getting an error when trying to build (master branch) on Python 3.7:

```
Installing collected packages: code-comment
  Running setup.py develop for code-comment
    Complete output from command /home/rob/projects/atarashi/.venv/bin/python -c "import setuptools, tokenize;__file__='/home/rob/projects/atarashi/.venv/src/code-comment/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --user not recognized
```
I'm able to build when I run the command with sudo, but this shouldn't be necessary per my understanding.

**Comment by GMishx** [comment]
Please check with #46

**Comment by GMishx** [comment]
Before building Atarashi, you need to install the dependencies. You can install either through `requirements.txt` or by running `sudo python3 setup.py install_deps`

I forgot to add it to the README

**Comment by mcjaeger** [comment]
I think it has been added to the readme @robguinness  if you would like to help us, you could consider confirming it is working and we could merge the PR.

**Comment by robguinness** [comment]
There is a mention of `pip install -r requirements.txt`, but only under the heading "Installing just dependencies". In any case, I can confirm that @GMishx's PR solves the initial problem related to this issue, so I think it can be merged and this issue closed. I could open a separate PR about the documentation issue, if you'd like.

**Comment by robguinness** [comment]
Sorry, I'm actually getting another issue now when trying to build:

```
Successfully installed numpy-1.15.4 pandas-0.23.4 python-dateutil-2.7.5 pytz-2018.9 setuptools-40.6.3 six-1.12.0 tqdm-4.29.0
Obtaining code_comment from git+https://github.com/amanjain97/code_comment#egg=code_comment
  Updating ./.venv/src/code-comment clone
Installing collected packages: code-comment
  Found existing installation: code-comment 0.1.0
    Not uninstalling code-comment at /home/rob/projects/forks/atarashi/.venv/lib/python3.7/site-packages, outside environment /home/rob/projects/forks/atarashi/.venv
    Can't uninstall 'code-comment'. No files were found to uninstall.
  Running setup.py develop for code-comment
    Complete output from command /home/rob/projects/forks/atarashi/.venv/bin/python -c "import setuptools, tokenize;__file__='/home/rob/projects/forks/atarashi/.venv/src/code-comment/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --user not recognized
    
    ----------------------------------------
  Can't roll back code-comment; was not uninstalled
Command "/home/rob/projects/forks/atarashi/.venv/bin/python -c "import setuptools, tokenize;__file__='/home/rob/projects/forks/atarashi/.venv/src/code-comment/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /home/rob/projects/forks/atarashi/.venv/src/code-comment/
Traceback (most recent call last):
  File "setup.py", line 187, in <module>
    setup(**metadata)
  File "/home/rob/projects/forks/atarashi/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 134, in run
    self.run_command('install_deps')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 92, in run
    subprocess.run(install_options + ['-e', package], check = True)
  File "/usr/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/rob/projects/forks/atarashi/.venv/bin/python', '-m', 'pip', 'install', '--upgrade', '--ignore-installed', '--user', '-e', 'git+https://github.com/amanjain97/code_comment#egg=code_comment']' returned non-zero exit status 1.
```
It seems this is a similar issue as above, except now it is related to building the dependency `code_comment`. Any ideas on how to resolve that?

**Comment by GMishx** [comment]
I have opened another PR #48. It implements PEP 518 to install dependencies. Can you please test it @robguinness? Hope this will work for you.

**Comment by robguinness** [comment]
Great! I will test this tomorrow, as it's getting late here.

**Comment by robguinness** [comment]
I can now confirm that this works. The build/installation process is now much smoother. Thanks!

**Comment by GMishx** [comment]
:fearful: I anticipated this but it did not occurred with me.

Anyway, let me check.

**Comment by GMishx** [comment]
Thank you for your patience @robguinness !
I have changed the location of non-python files and it should be working now. Can you please check once again?

**Comment by robguinness** [comment]
Hi! Sorry for the delays. I got pulled in other directions. I'm trying to get back to this work this week, and I will update you when I've tried it. Thanks for YOUR patience! ;-)
