### ISSUE TITLE
Build fails due to import error from nirjas

### ISSUE THREAD

**Issue by xavierfigueroav** [fossology/atarashi#92]
I get the following error:

```
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    from atarashi.build_deps import download_dependencies
  File "/home/xavierfigueroav/Documents/atarashi-project/atarashi/atarashi/build_deps.py", line 32, in <module>
    from atarashi.license.licensePreprocessor import LicensePreprocessor
  File "/home/xavierfigueroav/Documents/atarashi-project/atarashi/atarashi/license/licensePreprocessor.py", line 31, in <module>
    from atarashi.libs.commentPreprocessor import CommentPreprocessor
  File "/home/xavierfigueroav/Documents/atarashi-project/atarashi/atarashi/libs/commentPreprocessor.py", line 30, in <module>
    from nirjas import extract as commentExtract, LanguageMapper
ImportError: cannot import name 'LanguageMapper' from 'nirjas' (/home/xavierfigueroav/Documents/atarashi-project/atarashi/.env/lib/python3.8/site-packages/nirjas/__init__.py)
```

This happens when running `python setup.py build`, after cloning the repository and installing the dependencies.

**Comment by GMishx** [comment]
Just fixed the thing in Nirjas. Please install the latest version 1.0.1 and try again.
